-- `vegan-mundi`.CLASS definition

CREATE TABLE `CLASS` (
  `CLASS_ID` int NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` int NOT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `PHOTO` varchar(100) DEFAULT NULL,
  `PUBLISH_DATE` date DEFAULT NULL,
  `DISPLAY_ORDER` int DEFAULT NULL,
  PRIMARY KEY (`CLASS_ID`),
  KEY `CLASS_CLASS_CATEGORY_FK` (`CATEGORY_ID`),
  CONSTRAINT `CLASS_CLASS_CATEGORY_FK` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CLASS_CATEGORY` (`CATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- `vegan-mundi`.CLASS_CATEGORY definition

CREATE TABLE `CLASS_CATEGORY` (
  `CATEGORY_ID` int NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `PHOTO` varchar(1000) DEFAULT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DISPLAY_ORDER` int DEFAULT NULL,
  `LEVEL` varchar(100) DEFAULT NULL,
  `DESCRIPTION_ITEMS_LIST` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`CATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- `vegan-mundi`.CLASS_RECIPE definition

CREATE TABLE `CLASS_RECIPE` (
  `CLASS_ID` int NOT NULL,
  `RECIPE_ID` int NOT NULL,
  PRIMARY KEY (`CLASS_ID`,`RECIPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- `vegan-mundi`.DELIVERY_METHOD definition

CREATE TABLE `DELIVERY_METHOD` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DISPLAY_ORDER` int DEFAULT NULL,
  `ICON` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- `vegan-mundi`.GALLERY definition

CREATE TABLE `GALLERY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PHOTO` varchar(1000) DEFAULT NULL,
  `LABEL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- `vegan-mundi`.PRICE definition

CREATE TABLE `PRICE` (
  `PRICE_ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  `PRICE` decimal(6,2) DEFAULT NULL,
  `ICON` varchar(100) DEFAULT NULL,
  `GREAT_VALUE` tinyint(1) DEFAULT NULL,
  `ADDITIONAL_INFO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PRICE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- `vegan-mundi`.RECIPE definition

CREATE TABLE `RECIPE` (
  `RECIPE_ID` int NOT NULL AUTO_INCREMENT,
  `RECIPE_CATEGORY_ID` int NOT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `PHOTO` varchar(100) DEFAULT NULL,
  `VIDEO` varchar(100) DEFAULT NULL,
  `PUBLISH_DATE` date DEFAULT NULL,
  `DISPLAY_ORDER` int DEFAULT NULL,
  `KEYWORD` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`RECIPE_ID`),
  KEY `RECIPE_RECIPE_CATEGORY_FK` (`RECIPE_CATEGORY_ID`),
  CONSTRAINT `RECIPE_RECIPE_CATEGORY_FK` FOREIGN KEY (`RECIPE_CATEGORY_ID`) REFERENCES `RECIPE_CATEGORY` (`RECIPE_CATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- `vegan-mundi`.RECIPE_CATEGORY definition

CREATE TABLE `RECIPE_CATEGORY` (
  `RECIPE_CATEGORY_ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RECIPE_CATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- `vegan-mundi`.ACCOUNT definition

CREATE TABLE `ACCOUNT` (
  `EMAIL` varchar(200) NOT NULL,
  `FIRST_NAME` varchar(20) DEFAULT NULL,
  `LAST_NAME` varchar(60) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;