pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Node.js App-Test') {
            // Trigger the pipeline only if there are commits in the "server" folder
            when {
                changeset "**/server/**"
            }
            steps {
                // Use sshagent to access the SSH key stored in Jenkins credentials
                sshagent (credentials: ['ssh-key-application-server']) {
                    sh '''
                        scp -i /root/.ssh/vegan-mundi.pem -o StrictHostKeyChecking=no server/index.js ${EC2_USER}@${EC2_APP_HOST}:${REMOTE_DIR}/index.js
                        
                        ssh -i /root/.ssh/vegan-mundi.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_APP_HOST} '
                            . $HOME/.nvm/nvm.sh &&  # Load nvm
                            /home/ubuntu/.nvm/versions/node/v21.7.2/bin/pm2 restart server
                        '
                    '''
                }
            }
        }

        stage('List Files') {
            steps {
                sh 'ls -la server'
            }
        }       
    }
}