pipeline {
    agent any
    stages {
        stage('Deploy Node.js App') {
            // Trigger the pipeline only if there are changes in the "server" folder
            when {
                changeset "**/server/**"
            }
            steps {
                // Here, we assume you deploy the Node.js application to an EC2 instance
                sh '''
                echo "Deploying Node.js application..."
                '''
            }
        }
    }
}