pipeline {
    agent any
    stages {
        stage('Deploy Node.js App-Test') {
            // Trigger the pipeline only if there are coomits in the "server" folder
            when {
                changeset "**/server/**"
            }
            steps {
                sshagent (credentials: ['ssh-key-application-server']){
                    sh '''
                        echo "Deploying Node.js application to Test..."
                        scp -o StrictHostKeyChecking=no server/index.js ${EC2_USER}@${EC2_APP_HOST}:${REMOTE_DIR}/index.js
                    '''
                }
            }

        }
    }
}