SELECT RCP.RECIPE_ID, RCP.TITLE, RCP.DESCRIPTION, RCP.PHOTO, RCP.VIDEO, RCP.PUBLISH_DATE, RCP.DISPLAY_ORDER  
           FROM   
           CLASS CLS   
            INNER JOIN CLASS_RECIPE CLR ON  
              CLS.CLASS_ID = CLR.CLASS_ID   
              AND CLS.CATEGORY_ID = 1  
            INNER JOIN RECIPE RCP ON    
              CLR.RECIPE_ID = RCP.RECIPE_ID 
            ORDER BY DISPLAY_ORDER