version: '3.7'

services:
  jenkins:
    image: vegan-mundi
    container_name: jenkins
    user: "1000:1000"
    restart: on-failure
    volumes:
      - jenkins-home:/var/jenkins_home
      - /home/ubuntu/docker-jenkins:/home/ubuntu/docker-jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-home: